### ISSUE TITLE
Setup a Github Action to publish this package to pip

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/BO4E-python#3]
- [x] pip should build a pre-release package from develop branch
- [x] and a release package from master

**Comment by hf-krechan** [comment]
Is it still necessary that we build a pre-release from the development branch?
It would be possible, but another option would be to clone the repository and install it from the source.

**Comment by hf-kklein** [comment]
>Is it still necessary that we build a pre-release from the development branch?

OK for me if we don't.

**Comment by hf-krechan** [comment]
Then I would close this issue.
There is a workflow for the release and we have a tox development setup which installs the BO4E-python package in development mode (if you have the right folder structure, see [https://github.com/Hochfrequenz/wim-bee-backend/tree/develop](https://github.com/Hochfrequenz/wim-bee-backend/tree/develop))
