### ISSUE TITLE
Add tool to generate a changelog

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/BO4E-python#52]
Cause this is an open source package, we should have nice change logs.
[Towncrier](https://pypi.org/project/towncrier/) is a tool which can help us with this work.

**Comment by hf-kklein** [comment]
I mean the default is not too bad:
https://github.com/Hochfrequenz/BO4E-python/releases/tag/v0.0.13
what are you missing?

**Comment by hf-krechan** [comment]
Fair enough
