### ISSUE TITLE
Change repo settings to have only default/main branch

### ISSUE THREAD

**Issue by hf-kklein** [Hochfrequenz/BO4E-python#68]
Hi, since releases will be built by tagging commits on main and merges to main are not squashed: Is there still a need for the develop branch or could we maybe omit the develop->main merges?

**Comment by hf-kklein** [comment]
Suggestion:
- use only main, no develop (unless we have prereleases)
- use tags to mark releases, not commits/PRs to master

**Comment by hf-krechan** [comment]
Good question.
I thought it could be useful to collect more features on the develop branch and release multiple features at once.
Sometimes there are dependencies between features so it's nice to collect them first.
There is also still my hope to use a tool to get nice version change information.
But I am not sure if therefore a develop branch is necessary.

**Comment by hf-kklein** [comment]
Reopening: For simplicity I'd say we should go with only 1 branch as target (namely main). A second branch would make sense if we deployed something from it. For versioning we have tags. If we want to release multiple commits at once, just tag the last of them.

IMHO the develop branch doesn't add value atm.

**Comment by hf-kklein** [comment]
we discussed: this is a way we want to go. I'll change the repo settings accordingly.
